# Generated by Django 4.2.3 on 2023-08-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='meaning_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='flashcards',
            name='term_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
